apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ehoi
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.telegram: "-1001562404876"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ehoi

  source:
    repoURL: git@github.com:AndriyBodnar/tgBotHoi.git
    targetRevision: HEAD
    path: deploy/helm/funny-chart
  destination: 
    server: https://kubernetes.default.svc
    namespace: funny-hoi

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true