apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    plugin:
      name: kustomize-build-with-helm
    repoURL: https://github.com/oavramenk/argocd.git
    targetRevision: HEAD
    path: apps/add-on/cert-manager
  destination: 
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true