apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- letsencrypt_issuer.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.8.0
  releaseName: my-cert-manager
  namespace: cert-manager