apiVersion: kustomize.config.k8s.io/v1beta1

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.8.0
  releaseName: cert-manager
  namespace: cert-manager
  # includeCRDs: true 

resources:
# instal CRDs
- github.com/cert-manager/cert-manager/deploy/crds/crd-certificaterequests.yaml?ref=release-1.8
- github.com/cert-manager/cert-manager/deploy/crds/crd-certificates.yaml?ref=release-1.8
- github.com/cert-manager/cert-manager/deploy/crds/crd-challenges.yaml?ref=release-1.8
- github.com/cert-manager/cert-manager/deploy/crds/crd-clusterissuers.yaml?ref=release-1.8
- github.com/cert-manager/cert-manager/deploy/crds/crd-issuers.yaml?ref=release-1.8
- github.com/cert-manager/cert-manager/deploy/crds/crd-orders.yaml?ref=release-1.8
# install letsencrypt cluster issuer
- letsencrypt_issuer.yaml