apiVersion: kustomize.config.k8s.io/v1beta1

# helmCharts:
# - name: cert-manager
#   repo: https://charts.jetstack.io
#   version: v1.8.0
#   releaseName: cert-manager
#   namespace: cert-manager
#   includeCRDs: true 

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
# install letsencrypt cluster issuer
- letsencrypt_issuer.yaml