apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ehoi-build-image
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: -1001562404876
spec:
  project: ehoi

  source:
    repoURL: git@github.com:AndriyBodnar/tgBotHoi.git
    targetRevision: HEAD
    path: deploy/build
  destination: 
    server: https://kubernetes.default.svc
    namespace: funny-hoi

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true